"""
Configuration module for Invoice Scanner services.

Provides centralized configuration and constants.
"""

from .defines import (
    LOCAL_DATABASE_URL,
    LOCAL_DATABASE_HOST,
    LOCAL_DATABASE_PORT,
    LOCAL_DATABASE_USER,
    LOCAL_DATABASE_PASSWORD,
    LOCAL_DATABASE_NAME,
    BASE_DOCUMENTS_DIR,
    DOCUMENTS_RAW_DIR,
    DOCUMENTS_PROCESSED_DIR,
)

__all__ = [
    'LOCAL_DATABASE_URL',
    'LOCAL_DATABASE_HOST',
    'LOCAL_DATABASE_PORT',
    'LOCAL_DATABASE_USER',
    'LOCAL_DATABASE_PASSWORD',
    'LOCAL_DATABASE_NAME',
    'BASE_DOCUMENTS_DIR',
    'DOCUMENTS_RAW_DIR',
    'DOCUMENTS_PROCESSED_DIR',
]
